spring:
  application:
    name: kafka-rest-proxy
  profiles:
    active: dev
info:
  version: ${project.version}
endpoints:
  shutdown:
    enabled: true
---
server:
  port: 8080
---
spring:
  profiles: dev

---
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
---
  kafka:
    rest:
      proxy:
        schemaRegistryClient:
          endpoint: http://localhost:8081
